name: Deploy GitHub Pages

on:
  push:
    branches:       
      - master
      - feature/nuxt

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
          ref: 'github-pages-test'

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Push generated to github-pages branch
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git reset --hard remotes/origin/master
          git config --global user.email "elias.knodel@gmail.com"
          git config --global user.name "elias-knodel"
          yarn
          yarn generate
          mv dist/* .
          git add .
          git commit -m "Deploy github pages"
          git push --force
