name: Deploy GitHub Pages

on:
    push:
      branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ github.token }}
        ref: 'github-pages'
    - name: Deploy GitHub Pages
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - run: git reset --hard remotes/origin/master
    - run: git config --global user.email "elias.knodel@gmail.com"
    - run: git config --global user.name "elias-knodel"
    - run: npm install
    - run: npm run lint
    - run: npm run build
    - run: mv dist/**/* .
    - run: git push --force
